version: '3.8'

services:
  pocketpal:
    image: pocketpal_image
    container_name: pocketpal
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      # Gcloud Auth
      - ~/.config/:/root/.config:ro
      # Gcloud Docker Auth
      - ~/.docker/config.json:/root/.docker/config.json:ro
    restart: unless-stopped
