version: '2.3'

services:

  pocketpal:
    image: pocketpal_image
    container_name: pocketpal
    working_dir: /code
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/code
    ports:
      # Flask
      - "5000:5000"
      - "8080:8080"
    volumes:
      # Code
      - ./:/code
      # Data
      - ./data:/data
      # Temp artifacts
      - /tmp:/tmp
      # Gcloud Auth
      - ~/.config/:/root/.config
      # Gcloud Docker Auth
      - ~/.docker/config.json:/root/.docker/config.json
      # SSH Config for Git
      - ~/.ssh/:/root/.ssh
      # Git config for Git
      - ~/.gitconfig:/root/.gitconfig
    shm_size: '32gb'
    # command: tail /dev/null -f
